void SetBody()
{
	perror( "Set Body Called.\n" );
//	printf( "Enter the desired 3-character body type.\n" );
//	fflush( stdin );
//	fgets( body_input, sizeof( body_input ), stdin ); // Input new body type
//	printf( "Current body type : %s", body_input ); // Find a way to translate to perror

//	printf( "Making Changes...\n" );
//	fseek( InputFile, 18, SEEK_SET ); // Moving pointer for body - Only for PCFemale.CRT

//	printf( "%ld\n", ftell( InputFile ) ); // Find a way to translate to perror
//	fputs( body_input, InputFile );
	printf( "Done!\n" );
	perror( "Set Body Finished!\n" );
}
